[theme]
base = "light"
primaryColor = "#071d49"
backgroundColor = "#f3f5f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f1f3d"
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false
